service: lambda-lcr-game
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 2023329
  region: us-east-1

functions:
  play-game:
    handler: src/builds/app.game
    events:
      - eventBridge:
          pattern:
            source:
              - play-lcr
plugins:
  - serverless-offline
  - serverless-plugin-typescript
