service: api-game-lcr
frameworkVersion: "3"

provider:
 name: aws
 runtime: nodejs14.x
 lambdaHashingVersion: 2023320
 region: us-east-1

functions:
 main: # The name of the lambda function
   # The module 'handler' is exported in the file 'src/lambda'
   handler: dist/lambda.handler   
   events:
     - httpApi:
          method: any
          path: /{proxy+}
        

plugins:  
 - serverless-jetpack
 - serverless-offline